### ISSUE TITLE
Tech Debt: Update CI Workflow to Use JDK 17

### ISSUE THREAD

**Issue by Tarek-Bohdima** [Greenstand/treetracker-android#1113]
## Tech Debt: Update CI Workflow to Use JDK 17

**Description:**

The current CI workflow uses JDK 11, but the latest Android Gradle plugin requires JDK 17. This tech debt issue proposes updating the workflow to use JDK 17 to ensure compatibility and unblock the PR for updating the target SDK version to 34 (#1111 ).

**Proposed Solution:**

Update the `pull-request.yaml` workflow file to use `actions/setup-java@v3` with `java-version: '17'`.

**Benefits:**

* Ensures compatibility with the latest Android Gradle plugin.
* Unblocks the PR for updating the target SDK version.
* Keeps the CI environment up-to-date.

**Tasks:**

- [ ] Update the `pull-request.yaml` workflow file.
- [ ] Test the updated workflow.
- [ ] Create a pull request.

**Related Issues:**

- #1111  (Update target SDK version to 34)

**Describe the tech debt**
A clear and concise description of what the tech debt is.

**Impact of the tech debt**
A description of the impact this technical debt has on the application (e.g. performance, 
maintenance challenges) and its severity.

**Urgency**
How important it is to address it now versus later? If later should we even raise this ticket.

**Intentional versus accidental**
Is this introduced deliberately based on a trade-off to achieve a goal or shipping a feature?
If so, what was the decision made on when this debt is scheduled to be addressed. 
Please link the original issue that caused this intentional debt for context.

**Comment by EngrTaofeek** [comment]
Done
